## Exploring numpy
Exploring the Library Numpy which uses Arrays, Vectors and matrices. Numpy is written in C and fortran, which makes it very fast and efficient.

In [2]:
%matplotlib inline
import matplotlib.pyplot as plt
import numpy as np


You need to use numpy in order to read data from files or use a list, tuples, matrices oder funtion which return numpy arrays, such as arange, linespace, and more.

In [6]:
# a vector: the argument to the array funtion is a Python list
v = np.array([1,2,3,4])

v

array([1, 2, 3, 4])

In [8]:
# a matrix: the argument to the array function is a nested python list
M = np.array([[1,2],[3,4]])

M

array([[1, 2],
       [3, 4]])

The v and M objects are both of the type ndarray that the numpy module provides

In [9]:
type(v), type(M)

(numpy.ndarray, numpy.ndarray)

Teh dirrence between the v and M arrays is only their shapes. We can get information about the shape of an array by using the ndarray.shape property

In [10]:
v.shape

(4,)

In [11]:
M.shape

(2, 2)

In [12]:
M.size

4

In [14]:
np.shape(M)

(2, 2)

In [15]:
M.dtype

dtype('int64')

In [16]:
m[0,0] = "hello"

NameError: name 'm' is not defined

In [20]:
x,y = np.mgrid[0:5, 0:5]

In [21]:
x

array([[0, 0, 0, 0, 0],
       [1, 1, 1, 1, 1],
       [2, 2, 2, 2, 2],
       [3, 3, 3, 3, 3],
       [4, 4, 4, 4, 4]])

In [22]:
y

array([[0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4]])

In [23]:
# random data
from numpy import random
#uniform random numbers in [0:1]
random.rand(5,5)

array([[0.82653921, 0.34191857, 0.16469394, 0.1423819 , 0.83433333],
       [0.51447742, 0.00557249, 0.48933629, 0.86043754, 0.24907196],
       [0.65417344, 0.38366321, 0.49147158, 0.65613541, 0.78605192],
       [0.99918927, 0.04740298, 0.44604182, 0.97677271, 0.23596262],
       [0.00426154, 0.74350512, 0.80886953, 0.58357049, 0.02351251]])

In [25]:
# standart normal distributed random numbers
random.randn(5,5)

array([[ 1.80425265,  0.25652227, -0.74442038,  0.55159241, -0.69271021],
       [ 0.30296461,  0.92827271,  1.06235784,  0.10849377, -0.29941509],
       [ 0.03365199, -0.11507678, -0.08479879, -0.57909726, -0.17215238],
       [-0.54448075, -0.12224312, -1.31974762, -1.21165984, -1.09160027],
       [ 0.17580225, -0.23959762,  1.06459945,  0.45850342,  1.81754764]])

# File I/O
!head data.dat
data = genfromtxt('datasheet.dat')
